spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
        bindings:
          ordersReceived:
            consumer:
              enableDlq: true
      bindings:
        ordersToSend:
          destination: orders-to-send
        ordersReceived:
          group: orderReceivedGroup
          destination: orders-to-send
          consumer:
            max-attempts: 3



feign:
  client:
    config:
      feignName:
        loggerLevel: full
        errorDecoder: com.rios.pocspringcloudkafkaretry.infrastructure.CustomErrorDecoder